GerenciadorDeEstoque/urls.py
from django.contrib import admin
from django.urls import path, include
from stock.views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ProdutosListView.as_view(), name='Produtos-list'),
    path('pesquisa/', SearchView.as_view(), name='search'),
    path('cadastrar/', ProdutosCreateView.as_view(), name='cadastro'),
    path('reestocar/', SemEstoqueListView.as_view(), name='sem_estoque'),
    path('adicionar-estoque/<int:pk>/', AddStockView.as_view(), name='add-stock'),
    path('remover-estoque/<int:pk>/', RemoveStockView.as_view(), name='remove-stock'),
    path('usuarios/', include('django.contrib.auth.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stock/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Produtos(models.Model):
	Nome = models.CharField(max_length = 50)
	Descrição = models.TextField()
	Código = models.CharField(max_length=50)
	Imagem = models.ImageField(null=True, blank=True)
	Quantidade = models.PositiveIntegerField()

	def __str__(self):
		return self.Código + ' - ' + self.Nome

stock/views.py
from django.views.generic import ListView, DetailView
from stock.models import Produtos
from django.db.models import Q
from django.views.generic.edit import CreateView
from django.shortcuts import redirect
# Create your views here.

class ProdutosListView(ListView):
    model = Produtos

class SearchView(ListView):
    model = Produtos
    template_name = 'search.html'

    def get_queryset(self):
        query = self.request.GET.get('pesq')
        object_list = Produtos.objects.filter(
            Q(Nome__icontains = query) |
            Q(Descrição__icontains = query) |
            Q(Código__icontains = query))
        return object_list

class ProdutosCreateView(CreateView):
    model = Produtos
    fields = ['Nome', 'Descrição', 'Código', 'Imagem', 'Quantidade']

class SemEstoqueListView(ListView):
    model = Produtos

    def get_queryset(self):
        query = 0
        object_list = Produtos.objects.filter(Quantidade=0)
        return object_list

class AddStockView(DetailView):
    model = Produtos

    def post(self, request, *args, **kwargs):
        produtos = self.get_object()
        Quantidade = self.request.POST['Quantidade']
        produtos.Quantidade += int(Quantidade)
        produtos.save()
        return redirect('Produtos-list')

class RemoveStockView(DetailView):
    model = Produtos

    def post(self, request, *args, **kwargs):
        produtos = self.get_object()
        Quantidade = self.request.POST['Quantidade']
        produtos.Quantidade -= int(Quantidade)
        produtos.save()
        return redirect('Produtos-list')

stock/templates/stock/base.html
<!DOCTYPE html>
<html lang="pt">
<head>
  <title>Gerenciador de Estoque</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <style>
      #logo{
          float: left
      }
      #usuario	{
			float:	right;
			margin: 0 0 0px 0px;
		}
        #logo_total {
            background-color: lightgray;
        }
  </style>
</head>
<body>
  {% load static %}

<div id='logo_total' class='row'>
<div class= "col-sm-4"><a href='{% url "Produtos-list"%}'><img id ='logo' src="{% static 'logo.jpg' %}" height="110px"></a></div>
<div class= "col-sm-4">
  <center><h1>Gerenciador de Estoque</h1> </center>
</div>
<div class= "col-sm-4">
{% if request.user.is_authenticated %}
      {{ request.user.get_full_name }}
      <a id="usuario" href="{% url 'logout'%}">sair</a>
    {% else %}
      <a href='{% url "login" %}'><img id="usuario" src="{% static 'usuario.png' %}" alt="usuario" height="110px" width="110px"></a>
    {% endif %}
</div>
</div>

{% block content %}
{% endblock %}


  
  </body>
  </html>

stock/templates/stock/produtos_form.html
{% extends "stock/base.html" %}
{% block content %}
Por algum motivo esse codigo não envia imagens então para cadastrar acesse 127.0.0.1:8000/admin

<form method="POST">

{% csrf_token %}
<label for="id_Nome">Nome:</label><br>
<input type="text" name="Nome" maxlength="50" required="" id="id_Nome"><br>
<label for="id_Descrição">Descrição:</label><br>
<textarea name="Descrição" cols="40" rows="10" required="" id="id_Descrição"></textarea><br>
<label for="id_Código">Código:</label><br>
<input type="text" name="Código" maxlength="50" required="" id="id_Código"><br>
<label for="id_Imagem">Imagem:</label><br>
<input type="file" name="Imagem" accept="image/png, image/jpeg"  id="id_Imagem" multiple /> <br>
<label for="id_Quantidade">Quantidade:</label><br>
<input type="number" name="Quantidade" min="0" required="" id="id_Quantidade"><br>
<input type="submit" value="Cadastrar">

</form>

{% endblock %}

stock/templates/stock/produtos_list.html
{% extends "stock/base.html" %}
{% block content %}
<style>
form.example input[type=text] {
  padding: 10px;
  font-size: 17px;
  border: 1px solid grey;
  float: left;
  width: 80%;
  background: #f1f1f1;
}

form.example button {
  float: left;
  height: 47px;
  width: 20%;
  padding: 10px;
  background: #2196F3;
  color: white;
  font-size: 17px;
  border: 1px solid grey;
  border-left: none;
  cursor: pointer;
}

form.example button:hover {
  background: #0b7dda;
}

form.example::after {
  content: "";
  clear: both;
  display: table;
}

#Produtos{
  float: left;
}
</style>

<div class="container" style="margin-top:30px">
  <div class="row">
    <div class="col-sm-3">
        <form class="example" action="{% url 'search' %}" style="margin:auto;max-width:300px" method="get">
            <input type="text" placeholder="Pesquisar" name="pesq">
            <button type="Pesquisar"><i class="fa fa-search"></i></button>
          </form>
        <a class="btn btn-primary" href="{% url 'cadastro' %}">Cadastrar Produtos</a>
        <a class="btn btn-primary" href="{% url 'sem_estoque' %}">Produtos sem estoque</a>
        </div>

    {% for Produtos in object_list %}
    <div id='Produtos' class="col-sm-9">
      <h2>{{Produtos.Nome}}</h2>
      <div class='row'>
	  <div class= "col-sm-4">
      <h3 id='logo'>Em estoque: {{Produtos.Quantidade}}</h3></div>
      </div>
      <h5>Código: {{Produtos.Código}}</h5>
      {% if '{{Produtos.Imagem.url}}' != NULL %}
      <img class='img-fluid' src='{{Produtos.Imagem.url}}' height="300px" width="400px">
      {% else %}
      <img class='img-fluid' src='media/static/as.png' height="300px" width="400px">
      {% endif %}
      <p>{{Produtos.Descrição}}</p>
      <div class='row'>
        <div class= "col-sm-4">
      <form method="POST" action="{% url 'add-stock' Produtos.id %}">
        {% csrf_token %}
        <input type="number" name="Quantidade" min='1'>
        <input type="submit" value='Adicionar ao Estoque'>
      </form></div>
      <div class= "col-sm-4">
      <form method="POST" action="{% url 'remove-stock' Produtos.id %}">
          {% csrf_token %}
        <input type="number" name="Quantidade" min='1'>
        <input type="submit" value='Remover do Estoque'>
      </form></div>
      {% endfor %}
    </div>
  </div>
</div>
</div>


{% endblock %}